# Generated by Django 5.0.3 on 2024-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_spendings_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='wage',
            field=models.FloatField(),
        ),
    ]
